### ISSUE TITLE
search crash

### ISSUE THREAD

**Issue by rberiot** [gdesmott/karapulse#3]
```
[2019-02-17T09:14:57Z INFO  rocket::rocket] GET /api/search/J'aime application/json:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("fts5: syntax error near \"\'\""))', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by rberiot** [comment]
same issue with escaped search string:
`[2019-02-17T09:51:27Z INFO  rocket::rocket] GET /api/search/j%27aime application/json:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("fts5: syntax error near \"\'\""))', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
`

**Comment by gdesmott** [comment]
I can reproduce using the CLI tool: `cargo run --bin cli-client -- search "J'aime"`

**Comment by gdesmott** [comment]
What would be the proper SQL query?  Neither of those are working.

```
sqlite> SELECT songs.rowid, path, songs.artist, songs.title, length FROM songs, fts_songs WHERE fts_songs match "j''aime" AND fts_songs.rowid = songs.rowid ORDER BY RANK;
Error: fts5: syntax error near "'"
sqlite> SELECT songs.rowid, path, songs.artist, songs.title, length FROM songs, fts_songs WHERE fts_songs match "j\'aime" AND fts_songs.rowid = songs.rowid ORDER BY RANK;
Error: fts5: syntax error near "\"
sqlite> SELECT songs.rowid, path, songs.artist, songs.title, length FROM songs, fts_songs WHERE fts_songs match "j\'\'aime" AND fts_songs.rowid = songs.rowid ORDER BY RANK;
Error: fts5: syntax error near "\"
```

**Comment by gdesmott** [comment]
So this is working:

```
sqlite> SELECT songs.rowid, path, songs.artist, songs.title, length FROM songs, fts_songs WHERE fts_songs match '"j''aime"' AND fts_songs.rowid = songs.rowid ORDER BY RANK;
29548|/run/media/cassidy/LaCie/Karaoke/Rigmar Karaoke Collection March 2018 CDG+MP3/Francis Cabrel - Quand J'aime Une Fois, J'aime Pour Toujours [French Karaoke].mp3|Francis Cabrel|Quand J'aime Une Fois, J'aime|298
```

But this syntax breaks the multi-words search:

```
sqlite> SELECT songs.rowid, path, songs.artist, songs.title, length FROM songs, fts_songs WHERE fts_songs match '"nirvana smell"' AND fts_songs.rowid = songs.rowid ORDER BY RANK;
sqlite> 
```

Any idea? Looks like a FTS specific issue.

**Comment by gdesmott** [comment]
I think it should be ok now.

**Comment by rberiot** [comment]
![image](https://user-images.githubusercontent.com/65184/52938573-4ccfa900-3362-11e9-879d-36890053cea1.png)
